### ISSUE TITLE
Discord Title Message (Custom positing) - editing write files doesn't work

### ISSUE THREAD

**Issue by Link2TP** [LompeBoer/go-autocoins#2]
Your go-autocoins works fantastic. Just a very minor issue I have noticed (which would be cool if it was working):

Modifying the title part in the "writer" file under autocoins internal folders does not change the title message that is posted in Discord. If you modify it, it continues posting the original message. 

Have tried restarting the executable of course

**Comment by LompeBoer** [comment]
That should be working. I described the steps below how you can build your own version.

- Checkout/download the project code. Everything below assumes you're working from the project directory.
- Change this [line](https://github.com/LompeBoer/go-autocoins/blob/d5ececb2815ad12ae6c63d0bd2853730eb766d6f/internal/autocoins/writer.go#L123).
- Make sure [Go](https://golang.org/) is installed, run `go version` to check.
- Update autoCoins.json with your values.
- Run `go run cmd/autocoins/*.go` to test if your change is working.
- If it's working, create the executable `go build -o bin/go-autocoins.exe cmd/autocoins/*.go` (the .exe will be placed in the bin/ directory).  
  
Can you explain what the use case is for changing the title of the message?

**Comment by Link2TP** [comment]
Thank you for the swift reply, I will try this out when I have the opportunity. 
As for the use case, there isn't really one hence saying it was just a minor issue. Was basically playing around with modifying discord notifications (learning) & just happened to try it with your program as I also use WH :)

Thanks again.
